spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "1.2.0"

account:
  message: "Welcome to NearMe accounts related QA APIs "
  contactDetails:
    name: "Ankush - QA Lead"
    email: "ankush@nearme.com"
  onCallSupport:
    - (666) 2555-1234
    - (666) 523-1345