build:
  version: "3.3.0"

product:
  message: "Welcome to NearMe product related prod APIs "
  contactDetails:
    name: "Ansh - Prod Lead"
    email: "ansh@near.com"
  onCallSupport:
    - (444) 555-1234
    - (444) 523-1345
